# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
   # Flutter Pod

    copied_flutter_dir = File.join(__dir__, 'Flutter')
    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
    copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
    unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
      # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
      # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
      # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

      generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
      unless File.exist?(generated_xcode_build_settings_path)
        raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end
      generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
      cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

      unless File.exist?(copied_framework_path)
        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
      end
      unless File.exist?(copied_podspec_path)
        FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
      end
    end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  #target 'RunnerTests' do
  #  inherit! :search_paths
  #end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
